-- Insert blank pantheons (because there needs to be a pantheon for each great prophet)
INSERT INTO Types (Type, Kind)
  WITH counter as (SELECT 1 x UNION SELECT x + 1 FROM counter WHERE x < 13) 
  SELECT 'SDG_BLANK_PANTHEON' || x , 'KIND_BELIEF' FROM counter ;
 
INSERT INTO Beliefs (BeliefType, Name, Description, BeliefClassType) VALUES 
                    ("SDG_BLANK_PANTHEON1", "LOC_SDG_BLANK_PANTHEON", "LOC_SDG_BLANK_PANTHEON_DESCRIPTION", "BELIEF_CLASS_PANTHEON") ;

INSERT INTO Beliefs (BeliefType, Name, Description, BeliefClassType)
  WITH counter as (SELECT 2 x UNION SELECT x + 1 FROM counter WHERE x < 13) 
  SELECT 'SDG_BLANK_PANTHEON' || x , 'LOC_SDG_BLANK_PANTHEON2', 'LOC_SDG_BLANK_PANTHEON2_DESCRIPTION', 'BELIEF_CLASS_PANTHEON' FROM counter ;


INSERT INTO Types (Type, Kind) VALUES
				  ('SDG_GREAT_PERSON_INDIVIDUAL_MOSES', 'KIND_GREAT_PERSON_INDIVIDUAL'),                -- 
				  ('SDG_GREAT_PERSON_INDIVIDUAL_ELIJAH', 'KIND_GREAT_PERSON_INDIVIDUAL'),               -- 
				  ('SDG_GREAT_PERSON_INDIVIDUAL_PAUL_OF_TARSUS', 'KIND_GREAT_PERSON_INDIVIDUAL'),       -- 5-67

				  ('SDG_GREAT_PERSON_INDIVIDUAL_MARCION', 'KIND_GREAT_PERSON_INDIVIDUAL'),              -- 85-160
				  ('SDG_GREAT_PERSON_INDIVIDUAL_ARIUS', 'KIND_GREAT_PERSON_INDIVIDUAL'),                -- 250-336
				  ('SDG_GREAT_PERSON_INDIVIDUAL_JOHN_CHRYSOSTOM', 'KIND_GREAT_PERSON_INDIVIDUAL'),      -- 349-407
				  ('SDG_GREAT_PERSON_INDIVIDUAL_AUGUSTINE', 'KIND_GREAT_PERSON_INDIVIDUAL'),            -- 354-430
				  ('SDG_GREAT_PERSON_INDIVIDUAL_GREGORY_THE_GREAT', 'KIND_GREAT_PERSON_INDIVIDUAL'),    -- 540-604

				  ('SDG_GREAT_PERSON_INDIVIDUAL_JOSEPH_SMITH', 'KIND_GREAT_PERSON_INDIVIDUAL'),     -- 1805-1844
				  ('SDG_GREAT_PERSON_INDIVIDUAL_BAHAULLAH', 'KIND_GREAT_PERSON_INDIVIDUAL'),        -- 1817-1892
				  ('SDG_GREAT_PERSON_INDIVIDUAL_GEORGE_MACDONALD', 'KIND_GREAT_PERSON_INDIVIDUAL'), -- 1824-1905

                  ('SDG_GREAT_PERSON_INDIVIDUAL_CS_LEWIS', 'KIND_GREAT_PERSON_INDIVIDUAL'),         -- 1898-1963
				  ('SDG_GREAT_PERSON_INDIVIDUAL_MLK', 'KIND_GREAT_PERSON_INDIVIDUAL'),              -- 1929-1968
				  
				  ('SDG_GREAT_PERSON_INDIVIDUAL_SUN_MYUNG_MOON', 'KIND_GREAT_PERSON_INDIVIDUAL'),   -- 1920-2012
				  ('SDG_GREAT_PERSON_INDIVIDUAL_JOHN_PAUL_II', 'KIND_GREAT_PERSON_INDIVIDUAL'),     -- 1920-2005
				  
				  ('SDG_GREAT_PERSON_INDIVIDUAL_GARY_RANDALL', 'KIND_GREAT_PERSON_INDIVIDUAL') ;    -- 1949-2018

INSERT INTO GreatPersonIndividuals 
  (GreatPersonIndividualType, Name, GreatPersonClassType, EraType, Gender, ActionCharges, ActionRequiresOwnedTile, ActionEffectTileHighlighting) VALUES

  ('SDG_GREAT_PERSON_INDIVIDUAL_MOSES', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_MOSES', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_CLASSICAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_ELIJAH', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_ELIJAH', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_CLASSICAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_PAUL_OF_TARSUS', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_PAUL_OF_TARSUS', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_CLASSICAL', 'M', 0, 1, 1),
  
  ('SDG_GREAT_PERSON_INDIVIDUAL_MARCION', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_MARCION', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_MEDIEVAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_ARIUS', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_ARIUS', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_MEDIEVAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_JOHN_CHRYSOSTOM', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_JOHN_CHRYSOSTOM', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_MEDIEVAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_AUGUSTINE', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_AUGUSTINE', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_MEDIEVAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_GREGORY_THE_GREAT', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_GREGORY_THE_GREAT', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_MEDIEVAL', 'M', 0, 1, 1),

  ('SDG_GREAT_PERSON_INDIVIDUAL_JOSEPH_SMITH', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_JOSEPH_SMITH', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_INDUSTRIAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_BAHAULLAH', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_BAHAULLAH', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_INDUSTRIAL', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_GEORGE_MACDONALD', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_GEORGE_MACDONALD', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_INDUSTRIAL', 'M', 0, 1, 1),

  ('SDG_GREAT_PERSON_INDIVIDUAL_CS_LEWIS', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_CS_LEWIS', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_MODERN', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_MLK', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_MLK', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_MODERN', 'M', 0, 1, 1),

  ('SDG_GREAT_PERSON_INDIVIDUAL_SUN_MYUNG_MOON', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_SUN_MYUNG_MOON', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_ATOMIC', 'M', 0, 1, 1),
  ('SDG_GREAT_PERSON_INDIVIDUAL_JOHN_PAUL_II', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_JOHN_PAUL_II', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_ATOMIC', 'M', 0, 1, 1),

  ('SDG_GREAT_PERSON_INDIVIDUAL_GARY_RANDALL', 'LOC_SDG_GREAT_PERSON_INDIVIDUAL_GARY_RANDALL', 'GREAT_PERSON_CLASS_PROPHET', 'ERA_INFORMATION', 'M', 0, 1, 1) ;