INSERT INTO Parameters (ParameterId, Name, Description, 
Domain, DefaultValue, ConfigurationGroup, ConfigurationId, GroupId, Visible, ReadOnly,
SupportsSinglePlayer, SupportsLANMultiplayer, SupportsInternetMultiplayer, SupportsHotSeat, SupportsPlayByCloud,
ChangeableAfterGameStart, ChangeableAfterPlayByCloudMatchCreate, SortIndex) VALUES 


('SDG_OLYMPIC_PANTHEONS', 'LOC_SDG_OLYMPIC_PANTHEONS_NAME', 'LOC_SDG_OLYMPIC_PANTHEONS_DESC', 
'bool', 1, 'Game', 'SDG_OLYMPIC_PANTHEONS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 330),

('SDG_REMOVE_CONDEMN_HERETIC', 'LOC_SDG_REMOVE_CONDEMN_HERETIC_NAME', 'LOC_SDG_REMOVE_CONDEMN_HERETIC_DESC', 
'bool', 1, 'Game', 'SDG_REMOVE_CONDEMN_HERETIC', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 331),

('SDG_ONE_CLEANSE_INQUISITORS', 'LOC_SDG_ONE_CLEANSE_INQUISITORS_NAME', 'LOC_SDG_ONE_CLEANSE_INQUISITORS_DESC', 
'bool', 1, 'Game', 'SDG_ONE_CLEANSE_INQUISITORS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 332),

('SDG_DONT_NEED_INQUISITION', 'LOC_SDG_DONT_NEED_INQUISITION_NAME', 'LOC_SDG_DONT_NEED_INQUISITION_DESC', 
'bool', 1, 'Game', 'SDG_DONT_NEED_INQUISITION', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 333),

('SDG_INQUISITORS_FROM_SHRINES', 'LOC_SDG_INQUISITORS_FROM_SHRINES_NAME', 'LOC_SDG_INQUISITORS_FROM_SHRINES_DESC', 
'bool', 1, 'Game', 'SDG_INQUISITORS_FROM_SHRINES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 334),

('SDG_RELIGIOUS_UNITS_TWO_MOVES', 'LOC_SDG_RELIGIOUS_UNITS_TWO_MOVES_NAME', 'LOC_SDG_RELIGIOUS_UNITS_TWO_MOVES_DESC', 
'bool', 1, 'Game', 'SDG_RELIGIOUS_UNITS_TWO_MOVES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 335),

('SDG_NO_RELIGIOUS_SEA_SPIES', 'LOC_SDG_NO_RELIGIOUS_SEA_SPIES_NAME', 'LOC_SDG_NO_RELIGIOUS_SEA_SPIES_DESC', 
'bool', 1, 'Game', 'SDG_NO_RELIGIOUS_SEA_SPIES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 336),

('SDG_ALL_HS3_BUILDINGS', 'LOC_SDG_ALL_HS3_BUILDINGS_NAME', 'LOC_SDG_ALL_HS3_BUILDINGS_DESC', 
'bool', 1, 'Game', 'SDG_ALL_HS3_BUILDINGS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 337),

('SDG_CATHEDRALS_HOLD_RELICS', 'LOC_SDG_CATHEDRALS_HOLD_RELICS_NAME', 'LOC_SDG_CATHEDRALS_HOLD_RELICS_DESC', 
'bool', 1, 'Game', 'SDG_CATHEDRALS_HOLD_RELICS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 338),

('SDG_KOTOKUIN_TO_THEOLGY', 'LOC_SDG_KOTOKUIN_TO_THEOLGY_NAME', 'LOC_SDG_KOTOKUIN_TO_THEOLGY_DESC', 
'bool', 1, 'Game', 'SDG_KOTOKUIN_TO_THEOLGY', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 339),


('SDG_ALL_CUSTOM_NAMES', 'LOC_SDG_ALL_CUSTOM_NAMES_NAME', 'LOC_SDG_ALL_CUSTOM_NAMES_DESC', 
'bool', 0, 'Game', 'SDG_ALL_CUSTOM_NAMES', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 350),

('SDG_DOUBLE_BELIEFS', 'LOC_SDG_DOUBLE_BELIEFS_NAME', 'LOC_SDG_DOUBLE_BELIEFS_DESC', 
'bool', 0, 'Game', 'SDG_DOUBLE_BELIEFS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 351),

('SDG_COMBAT_DOESNT_PRESSURE', 'LOC_SDG_COMBAT_DOESNT_PRESSURE_NAME', 'LOC_SDG_COMBAT_DOESNT_PRESSURE_DESC', 
'bool', 0, 'Game', 'SDG_COMBAT_DOESNT_PRESSURE', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 352),

('SDG_BUY_HSBUILDINGS_WITH_FAITH', 'LOC_SDG_BUY_HSBUILDINGS_WITH_FAITH_NAME', 'LOC_SDG_BUY_HSBUILDINGS_WITH_FAITH_DESC', 
'bool', 0, 'Game', 'SDG_BUY_HSBUILDINGS_WITH_FAITH', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 353),

('SDG_MARTYRS_LOSE_CS', 'LOC_SDG_MARTYRS_LOSE_CS_NAME', 'LOC_SDG_MARTYRS_LOSE_CS_DESC', 
'bool', 0, 'Game', 'SDG_MARTYRS_LOSE_CS', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 354),

('SDG_REMOVE_HEATHEN_CONVERSION', 'LOC_SDG_REMOVE_HEATHEN_CONVERSION_NAME', 'LOC_SDG_REMOVE_HEATHEN_CONVERSION_DESC', 
'bool', 0, 'Game', 'SDG_REMOVE_HEATHEN_CONVERSION', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 355),

('SDG_RELIGION_TESTER_HELPER', 'LOC_SDG_RELIGION_TESTER_HELPER_NAME', 'LOC_SDG_RELIGION_TESTER_HELPER_DESC', 
'bool', 0, 'Game', 'SDG_RELIGION_TESTER_HELPER', 'AdvancedOptions', 1, 0, 
1, 1, 1, 1, 1, 
0, 0, 356)

;