-- ('', '', 'en_US'),


INSERT OR REPLACE INTO LocalizedText 
(Tag, Text, Language) VALUES

('LOC_POLICY_SCRIPTURE_DESCRIPTION', '+100% Holy Site adjacency bonuses. (view in civilopedia for pantheon details)' , 'en_US'),
('LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_SCRIPTURE_CHAPTER_HISTORY_PARA_1', '***Olympic Pantheons***[NEWLINE]This policy will be applied to the faith bonuses from:[NEWLINE]Alpheus[NEWLINE]Aphrodite (Holy Site only)[NEWLINE]Gaia[NEWLINE]Helios[NEWLINE]Hestia[NEWLINE]Pan[NEWLINE]Persephone[NEWLINE]Poseidon[NEWLINE]Zeus (Holy Site only)[NEWLINE][NEWLINE]This policy is not applied to the faith bonuses from:[NEWLINE]Apollo[NEWLINE]Ares[NEWLINE]Artemis[NEWLINE]Athena[NEWLINE]Atlas[NEWLINE]Demeter[NEWLINE]Dionysus[NEWLINE]Hades[NEWLINE]Hephaestus[NEWLINE]Hera' , 'en_US'),
('LOC_PEDIA_GOVERNMENTS_PAGE_POLICY_SCRIPTURE_CHAPTER_HISTORY_PARA_2', 'The oldest religious text found so far dates to ancient Sumer around 2600 BC. It was the first example of scripture, a text that is considered to be sacred or central to a religious tradition. The oldest of a still existing religion is likely the Rigveda of Hinduism, composed between 1700 and 1100 BC. The claim of God''s (whoever it may be) Word "made manifest" is an undeniable selling point to would-be converts; it is not surprising that the five largest existing religions all have a primary scripture: Buddhism (the Tripitaka), Hinduism (Vedas and Upanishads), Islam (Qur’an), Judaism (Tanakh), and Christianity (Bible).' , 'en_US'),


('LOC_OP_ALPHEUS', 'Alpheus', 'en_US'),
('LOC_OP_ALPHEUS_DESCRIPTION', 'River --> [ICON_Gold][NEWLINE](+1 Gold from River tiles)[NEWLINE]Holy Site districts get +5 [ICON_Faith] Faith from an adjacent River', 'en_US'),
('LOC_OP_DISTRICT_RIVER_FAITH', '+{1_num} [ICON_Faith] Faith from Alpheus', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ALPHEUS_CHAPTER_HISTORY_PARA_1', 'Alpheus was a river (the modern Alfeios River) and river god. Like most river gods, he is a son of Oceanus and Tethys. Telegone, daughter of Pharis, bore his son, the king Orsilochus. Through him, Alpheus was the grandfather of Diocles, and great-grandfather of a pair of soldiers, Crethon and Orsilochus, who were slain by Aeneas during the Trojan War.  Alpheus was also the river which Heracles, in the fifth of his labours, rerouted in order to clean the filth from the Augean Stables in a single day, a task which had been presumed to be impossible.', 'en_US'),

('LOC_OP_APHRODITE', 'Aphrodite', 'en_US'),
('LOC_OP_APHRODITE_DESCRIPTION', 'Breathtaking --> [ICON_Faith][ICON_Faith][NEWLINE](+2 Faith from tiles with Breathtaking Appeal)[NEWLINE]Districts with Breathtaking Appeal get +2 [ICON_Faith] Faith', 'en_US'),
('LOC_OP_DISTRICT_APPEAL_FAITH', '+{1_num} [ICON_Faith] Faith from Aphrodite', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_APHRODITE_CHAPTER_HISTORY_PARA_1', 'Aphrodite is a goddess associated with love, beauty, pleasure, and procreation. In Hesiod''s Theogony, Aphrodite is born off the coast of Cythera from the foam produced by Uranus''s genitals, which his son Cronus has severed and thrown into the sea. In Homer''s Iliad, however, she is the daughter of Zeus and Dione.[NEWLINE][NEWLINE]Aphrodite was married to Hephaestus, the god of blacksmiths and metalworking. Despite this, Aphrodite was frequently unfaithful to him and had many lovers; in the Odyssey, she is caught in the act of adultery with Ares, the god of war.', 'en_US'),

('LOC_OP_APOLLO', 'Apollo', 'en_US'),
('LOC_OP_APOLLO_DESCRIPTION', 'Pastures --> [ICON_Production][ICON_Culture][ICON_Culture][NEWLINE](+1 Production and +2 Culture from Pastures)[NEWLINE]Pastures get +5 [ICON_Faith] Faith when next to a Holy Site[NEWLINE]The Oracle gets +5 [ICON_Faith] Faith', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_APOLLO_CHAPTER_HISTORY_PARA_1', 'Apollo is one of the most important and complex of the Olympian deities. The ideal of the kouros (a beardless, athletic youth), Apollo has been variously recognized as a god of music, truth and prophecy, healing, the sun and light, plague, poetry, and more. Apollo is the son of Zeus and Leto, and has a twin sister, the chaste huntress Artemis.[NEWLINE][NEWLINE]Among other things, he is the patron defender of herds and flocks. He is also connected with the fertility of cattle.', 'en_US'),

('LOC_OP_ARES', 'Ares', 'en_US'),
('LOC_OP_ARES_DESCRIPTION', 'No war weariness[NEWLINE]Land military units in foreign territory:[NEWLINE][ICON_Bullet]+6[ICON_STRENGTH]/[ICON_Ranged]/[ICON_Bombard] when attacking[NEWLINE][ICON_Bullet]Kills give you [ICON_Faith] equal to the defeated unit''s base [ICON_STRENGTH][NEWLINE]Holy Sites next to an Encampment get +10 [ICON_Faith] Faith', 'en_US'),
('LOC_OP_ABILITY_ARES_FOREIGN_STRENGTH_NAME', 'Ares: Foreign Strength', 'en_US'),
('LOC_OP_ABILITY_ARES_FOREIGN_STRENGTH_DESCRIPTION', 'Land military units in foreign territory: +6[ICON_STRENGTH]/[ICON_Ranged]/[ICON_Bombard] when attacking', 'en_US'),
('LOC_OP_ARES_FOREIGN_STRENGTH_COMBAT_DESCRIPTION', '+{1_Value} Ares', 'en_US'),
('LOC_OP_ABILITY_ARES_FAITH_ON_KILL_NAME', 'Ares: Faith on Kill', 'en_US'),
('LOC_OP_ABILITY_ARES_FAITH_ON_KILL_DESCRIPTION', 'Land military units in foreign territory:Kills give you [ICON_Faith] according to the defeated unit''s base', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ARES_CHAPTER_HISTORY_PARA_1', 'Ares is the god of war; son of Zeus and Hera. In Greek literature, he often represents the physical or violent and untamed aspect of war, in contrast to his sister, the armored Athena, whose functions as a goddess of intelligence include military strategy and generalship.[NEWLINE][NEWLINE]The Greeks were ambivalent toward Ares: although he embodied the physical valor necessary for success in war, he was a dangerous force, "overwhelming, insatiable in battle, destructive, and man-slaughtering."', 'en_US'),


('LOC_OP_ARTEMIS', 'Artemis', 'en_US'),
('LOC_OP_ARTEMIS_DESCRIPTION', 'Camps --> [ICON_Food][ICON_Food][ICON_Production][ICON_Gold][NEWLINE](+2 Food, +1 Production, and +1 Gold from Camps)[NEWLINE]Camps get +5 [ICON_Faith] Faith when next to a Holy Site[NEWLINE]The Temple of Artemis gets +5 [ICON_Faith] Faith', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ARTEMIS_CHAPTER_HISTORY_PARA_1', 'Artemis was the daughter of Zeus and Leto, and the twin sister of Apollo. She was the goddess of the hunt, wild animals, wilderness, childbirth, virginity and protector of young girls, bringing and relieving disease in women; she often was depicted as a huntress carrying a bow and arrows. The deer and the cypress were sacred to her.', 'en_US'),

('LOC_OP_ATHENA', 'Athena', 'en_US'),
('LOC_OP_ATHENA_DESCRIPTION', '[ICON_RESOURCE_BANANAS][ICON_RESOURCE_CITRUS][ICON_RESOURCE_COTTON][ICON_RESOURCE_DYES][ICON_RESOURCE_OLIVES][ICON_RESOURCE_SILK][ICON_RESOURCE_SUGAR] --> [ICON_Production][ICON_Science][ICON_Science][NEWLINE](+1 Production and +2 Science from Banana, Citrus, Cotton, Dyes, Olives, Silk, and Sugar Plantations)[NEWLINE]These also get +5 [ICON_Faith] Faith when next to a Holy Site', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ATHENA_CHAPTER_HISTORY_PARA_1', 'Athena is a goddess associated with wisdom, craft, weaving, and warfare. She was also a warrior goddess, and was believed to lead soldiers into battle. Athena was also the patron goddess of heroic endeavor; aiding Perseus, Heracles, Bellerophon, and Jason in their adventures.[NEWLINE][NEWLINE]Athena was born from the head of her father Zeus and was regarded as the protectress of various cities across Greece (particularly the city of Athens). Since the Renaissance, Athena has become an international symbol of wisdom, the arts, and classical learning. Western artists and allegorists have often used Athena as a symbol of freedom and democracy.', 'en_US'),

('LOC_OP_ATLAS', 'Atlas', 'en_US'),
('LOC_OP_ATLAS_DESCRIPTION', 'Quarries --> [ICON_Production][ICON_Production][ICON_Faith][NEWLINE](+2 Production and +1 Faith from Quarries)[NEWLINE]Quarries get +4 [ICON_Faith] Faith when next to a Holy Site', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ATLAS_CHAPTER_HISTORY_PARA_1', 'Atlas was a Titan condemned to hold up the sky for eternity. Although associated with various places, he became commonly identified with the Atlas Mountains in northwest Africa (modern-day Morocco, Algeria and Tunisia). Atlas was the son of the Titan Iapetus and the Oceanid Asia or Clymene. He had many children, mostly daughters, the Hesperides, the Hyades, the Pleiades, and the nymph Calypso who lived on the island Ogygia. Atlas stood at the ends of the earth towards the west.  ''Atlantic Ocean'' means ''Sea of Atlas'', while ''Atlantis'' means ''island of Atlas''.', 'en_US'),

('LOC_OP_DEMETER', 'Demeter', 'en_US'),
('LOC_OP_DEMETER_DESCRIPTION', 'Farms --> [ICON_Food][NEWLINE](+1 Food from Farms, including Terrace Farms)[NEWLINE]Farms get +3 [ICON_Faith] Faith when next to a Holy Site', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_DEMETER_CHAPTER_HISTORY_PARA_1', 'Demeter is the goddess of the grain, agriculture, harvest, growth, and nourishment, who presided over grains and the fertility of the earth. Though Demeter is often described simply as the goddess of the harvest, she presided also over the sacred law, and the cycle of life and death.', 'en_US'),

('LOC_OP_DIONYSUS', 'Dionysus', 'en_US'),
('LOC_OP_DIONYSUS_DESCRIPTION', '[ICON_RESOURCE_COCOA][ICON_RESOURCE_COFFEE][ICON_RESOURCE_INCENSE][ICON_RESOURCE_SPICES][ICON_RESOURCE_TEA][ICON_RESOURCE_TOBACCO][ICON_RESOURCE_WINE] --> [Icon_Amenities][Icon_Amenities][Icon_Amenities]...[NEWLINE](+100 Amenities for this city from Plantations on Cocoa, Coffee, Incense, Spices, Tea, Tobacco, and Wine Plantations)[NEWLINE]These also get +5 [ICON_Faith] Faith when next to a Holy Site', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_DIONYSUS_CHAPTER_HISTORY_PARA_1', 'Dionysus is the god of the grape-harvest, winemaking and wine, of fertility, ritual madness, religious ecstasy and theatre. He is a son of Zeus and the mortal Semele, thus semi-divine or heroic. Wine played an important role in Greek culture, and the cult of Dionysus was the main religious focus for its unrestrained consumption. He is a major, popular figure of Greek mythology and religion, and included in some lists of the twelve Olympians, as the last of their number, and the only god born from a mortal mother.[NEWLINE][NEWLINE]Dionysus is represented by city religions as the protector of those who do not belong to conventional society and he thus symbolizes the chaotic, dangerous and unexpected, everything which escapes human reason and which can only be attributed to the unforeseeable action of the gods. As Eleutherios (''the liberator''), his wine, music and ecstatic dance free his followers from self-conscious fear and care, and subvert the oppressive restraints of the powerful. Those who partake of his mysteries are possessed and empowered by the god himself. His festivals were the driving force behind the development of Greek theatre.', 'en_US'),

('LOC_OP_GAIA', 'Gaia', 'en_US'),
('LOC_OP_GAIA_DESCRIPTION', 'Rainforest --> [ICON_Food][NEWLINE](+1 Food from Rainforest tiles)[NEWLINE]Holy Site districts get +2 [ICON_Faith] Faith from adjacent Rainforest tiles', 'en_US'),
('LOC_OP_DISTRICT_JUNGLE_FAITH', '+{1_num} [ICON_Faith] Faith from Gaia', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_GAIA_CHAPTER_HISTORY_PARA_1', 'Gaia is the personification of the Earth and one of the Greek primordial deities. Gaia is the ancestral mother of all life: the primal Mother Earth goddess. She is the immediate parent of Uranus (the sky), from whose sexual union she bore the Titans (themselves parents of many of the Olympian gods) and the Giants, and of Pontus (the sea), from whose union she bore the primordial sea gods. Her equivalent in the Roman pantheon was Terra.', 'en_US'),

('LOC_OP_HADES', 'Hades', 'en_US'),
('LOC_OP_HADES_DESCRIPTION', 'Luxury/Bonus Mines --> [ICON_Production][ICON_Gold][ICON_Gold][ICON_Gold][ICON_Gold][ICON_Gold][NEWLINE](+1 Production and +5 Gold from Mines over Luxury and Bonus resources)[NEWLINE]These mines get +5 [ICON_Faith] Faith when next to a Holy Site', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HADES_CHAPTER_HISTORY_PARA_1', 'Hades was the chthonic god of the underworld, which eventually took his name. He was the eldest son of Cronus and Rhea, although the last son regurgitated by his father. He and his brothers Zeus and Poseidon defeated their father''s generation of gods, the Titans, and claimed rulership over the cosmos. Hades received the underworld, Zeus the sky, and Poseidon the sea, with the solid earth available to all three concurrently. Hades was often portrayed with his three-headed guard dog Cerberus.[NEWLINE][NEWLINE]Perhaps from fear of pronouncing his name, around the 5th century BC, the Greeks started referring to Hades as Pluto, with a root meaning ''wealthy'', considering that from the underground come riches (e.g., fertile crops, precious metals and so on). More elaborate names of the same genre were Ploutodotes or Ploutodoter meaning ''giver of wealth''.', 'en_US'),

('LOC_OP_HELIOS', 'Helios', 'en_US'),
('LOC_OP_HELIOS_DESCRIPTION', 'Desert --> [ICON_FOOD][ICON_PRODUCTION][ICON_FAITH][ICON_Gold][NEWLINE](+1 Food, +1 Production, +1 Faith, and +1 Gold from Desert tiles that do not have an Oasis or Floodplains)[NEWLINE]Holy Site districts get +1 [ICON_Faith] Faith from adjacent Desert tiles[NEWLINE]The Colossus gets +5 [ICON_Faith] Faith', 'en_US'),
('LOC_OP_DISTRICT_DESERT_FAITH', '+{1_num} [ICON_Faith] Faith from Helios', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HELIOS_CHAPTER_HISTORY_PARA_1', 'Helios is the god of the Sun. He is the son of the Titan Hyperion and the Titaness Theia and brother of the goddesses Selene, the moon, and Eos, the dawn.[NEWLINE][NEWLINE]Helios is a handsome young man crowned with the shining aureole of the Sun, who drove the chariot of the sun across the sky each day to earth-circling Oceanus and through the world-ocean returned to the East at night.', 'en_US'),

('LOC_OP_HEPHAESTUS', 'Hephaestus', 'en_US'),
('LOC_OP_HEPHAESTUS_DESCRIPTION', 'Strategic Mines --> [ICON_Production][ICON_Science][ICON_Culture][ICON_Faith][ICON_Gold][NEWLINE](+1 Production, +1 Science, +1 Culture, +1 Faith, and +1 Gold from Mines over Strategic resources)[NEWLINE]These mines get +5 [ICON_Faith] Faith when next to a Holy Site', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HEPHAESTUS_CHAPTER_HISTORY_PARA_1', 'Hephaestus is the Greek god of blacksmiths, metalworking, carpenters, craftsmen, artisans, sculptors, metallurgy, fire, and volcanoes. Hephaestus was either the son of Zeus and Hera or he was Hera''s parthenogenous child, rejected by his mother because of his deformity and thrown off Mount Olympus and down to earth.[NEWLINE][NEWLINE]As a smithing god, Hephaestus made all the weapons of the gods in Olympus. He served as the blacksmith of the gods, and was worshipped in the manufacturing and industrial centers of Greece, particularly Athens.', 'en_US'),

('LOC_OP_HERA', 'Hera', 'en_US'),
('LOC_OP_HERA_DESCRIPTION', 'Always loyal[NEWLINE](Your cities are immune to loyalty pressure)[NEWLINE]Holy Sites receive +3/7/12/18/25/33 [ICON_Faith] Faith based on the number of governor titles the city''s governor has', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HERA_CHAPTER_HISTORY_PARA_1', 'Hera is the goddess of women, marriage, family, and childbirth, one of the Twelve Olympians and the sister-wife of Zeus. She is the daughter of the Titans Cronus and Rhea. Hera rules over Mount Olympus as queen of the gods. A matronly figure, Hera served as both the patroness and protectress of married women, presiding over weddings and blessing marital unions. One of Hera''s defining characteristics is her jealous and vengeful nature against Zeus'' numerous lovers and illegitimate offspring, as well as the mortals who cross her. Yet she never leaves Zeus...', 'en_US'),

('LOC_OP_HERMES', 'Hermes', 'en_US'),
('LOC_OP_HERMES_DESCRIPTION', 'Roads --> Free to capital, Faster // Harvest --> [ICON_Faith][NEWLINE](Your cities within trade route range automatically have a road to your capital. Roads in your territory are one level more advanced than usual (e.g. classical instead of ancient).[NEWLINE]Harvesting a resource or removing a feature receives [ICON_Faith] Faith equal to the other yield''s quantity.)', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HERMES_CHAPTER_HISTORY_PARA_1', 'Hermes is the god of trade, heraldry, merchants, commerce, roads, sports, travelers, and athletes; the son of Zeus and the Pleiad Maia, he was the second youngest of the Olympian gods (Dionysus being the youngest).[NEWLINE][NEWLINE]Hermes was the emissary and messenger of the gods. He was also the divine ''trickster'' and the god of boundaries and the transgression of boundaries, the patron of herdsmen, thieves, graves, and heralds. He is described as moving freely between the worlds of the mortal and divine, and was the conductor of souls into the afterlife.  He was also viewed as the protector and patron of roads and travelers.', 'en_US'),

('LOC_OP_HESTIA', 'Hestia', 'en_US'),
('LOC_OP_HESTIA_DESCRIPTION', 'Forest --> [ICON_Gold][NEWLINE](+1 Gold from Forest tiles)[NEWLINE]Holy Site districts get +1 [ICON_Faith] Faith from adjacent Forest tiles', 'en_US'),
('LOC_OP_DISTRICT_FOREST_FAITH', '+{1_num} [ICON_Faith] Faith from Hestia', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_HESTIA_CHAPTER_HISTORY_PARA_1', 'Hestia is a virgin goddess of the hearth, architecture, and the right ordering of domesticity, the family, the home, and the state. She is a daughter of Kronos and Rhea. Hestia received the first offering at every sacrifice in the household. The hearth of the prytaneum functioned as her official sanctuary. With the establishment of a new colony, flame from Hestia''s public hearth in the mother city would be carried to the new settlement.', 'en_US'),

('LOC_OP_PAN', 'Pan', 'en_US'),
('LOC_OP_PAN_DESCRIPTION', 'Reeds --> [ICON_Culture][ICON_Culture][NEWLINE](+2 Culture from Marsh, Oasis, and Floodplain tiles)[NEWLINE]Holy Site districts get +2 [ICON_Faith] Faith from adjacent Marsh, Oasis, and Floodplain tiles', 'en_US'),
('LOC_OP_DISTRICT_REEDS_FAITH', '+{1_num} [ICON_Faith] Faith from Pan', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_PAN_CHAPTER_HISTORY_PARA_1', 'Pan is the god of the wild, shepherds and flocks, nature of mountain wilds, rustic music and impromptus, and companion of the nymphs. He has the hindquarters, legs, and horns of a goat, in the same manner as a faun or satyr. With his homeland in rustic Arcadia, he is also recognized as the god of fields, groves, wooded glens and often affiliated with sex; because of this, Pan is connected to fertility and the season of spring. The ancient Greeks also considered Pan to be the god of theatrical criticism.[NEWLINE][NEWLINE]The pan flute is named after Pan. Syrinx, a forest Nymph attempted to escape the affection of god Pan and was transformed in to water-reed. Then, Pan cut several reeds, placed them in parallel one next to the other, bound them together, and made a melodic musical instrument. Ancient Greeks called this instrument Syrinx, in honour of the Muse, and Pandean, or Pan-pipes and Pan-flute, after Pan. The Syrinx, a predominantly pastoral instrument for the Greeks, was adopted by the Etruscans who played it at their festivals and banquets; the Etruscans called it fistula. The Romans adopted the Syrinx from the Greeks and the Etruscans, and they too played it at their banquets, festivals, as well as in religious and funeral processions.', 'en_US'),

('LOC_OP_PERSEPHONE', 'Persephone', 'en_US'),
('LOC_OP_PERSEPHONE_DESCRIPTION', 'Tundra & Snow --> [ICON_Food][ICON_PRODUCTION][ICON_Faith] [NEWLINE](+1 Food, +1 Production, and +1 Faith from Tundra and Snow tiles)[NEWLINE]Holy Site districts get +1 [ICON_Faith] Faith from adjacent Tundra and Snow tiles', 'en_US'),
('LOC_OP_DISTRICT_SNOW_OR_TUNDRA_FAITH', '+{1_num} [ICON_Faith] Faith from Persephone', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_PERSEPHONE_CHAPTER_HISTORY_PARA_1', 'Persephone is the daughter of Zeus and Demeter. Homer describes her as the formidable, venerable majestic princess of the underworld, who carries into effect the curses of men upon the souls of the dead. She became the queen of the underworld through her abduction by and subsequent marriage to Hades, the god of the underworld. Her abduction is the personification of winter, withdrawing each year after harvest.', 'en_US'),

('LOC_OP_POSEIDON', 'Poseidon', 'en_US'),
('LOC_OP_POSEIDON_DESCRIPTION', 'Ocean --> [ICON_Production][ICON_Production][ICON_Production][ICON_Faith] // Horses --> [ICON_Faith][NEWLINE](+3 Production, and +1 Faith on Ocean tiles. +1 Faith on Horse tiles)[NEWLINE]Holy Site districts get +2 [ICON_Faith] Faith from adjacent Coast/Ocean tiles', 'en_US'),
('LOC_OP_DISTRICT_WATER_FAITH', '+{1_num} [ICON_Faith] Faith from Poseidon', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_POSEIDON_CHAPTER_HISTORY_PARA_1', 'Poseidon was god of the Sea and other waters; of earthquakes; and of horses. Poseidon was protector of seafarers, and of many cities and colonies. In Homer''s Iliad, Poseidon supports the Greeks against the Trojans during the Trojan War. In the Odyssey, during the sea-voyage from Troy back home to Ithaca, the Greek hero Odysseus provokes Poseidon''s fury by blinding his son the Cyclops, resulting in Poseidon punishing him with storms, the complete loss of his ship and companions, and a ten-year delay. The island of Atlantis was Poseidon''s domain.', 'en_US'),

('LOC_OP_ZEUS', 'Zeus', 'en_US'),
('LOC_OP_ZEUS_DESCRIPTION', 'Mountains --> +1 adjacency to districts[NEWLINE](Mountains provide a +1 adjacency bonus to Aerodromes[ICON_Production], Aqueducts[ICON_Food], Campuses[ICON_Science], Commercial Hubs[ICON_Gold], Encampments[ICON_Production], Entertainment Complexes[ICON_Culture], Harbors[ICON_Gold], Holy Sites[ICON_Faith], Industrial Zones[ICON_Production], Neighborhoods[ICON_Faith], Theater Squares[ICON_Culture] and Water Parks[ICON_Science])[NEWLINE]The Statue of Zeus gets +5 [ICON_Faith] Faith', 'en_US'),
('LOC_OP_DISTRICT_MOUNTAIN_PRODUCTION', '+{1_num} [ICON_Production] Production from Zeus', 'en_US'),
('LOC_OP_DISTRICT_MOUNTAIN_SCIENCE', '+{1_num} [ICON_Science] Science from Zeus', 'en_US'),
('LOC_OP_DISTRICT_MOUNTAIN_CULTURE', '+{1_num} [ICON_Culture] Culture from Zeus', 'en_US'),
('LOC_OP_DISTRICT_MOUNTAIN_FAITH', '+{1_num} [ICON_Faith] Faith from Zeus', 'en_US'),
('LOC_OP_DISTRICT_MOUNTAIN_FOOD', '+{1_num} [ICON_Food] Food from Zeus', 'en_US'),
('LOC_OP_DISTRICT_MOUNTAIN_GOLD', '+{1_num} [ICON_Gold] Gold from Zeus', 'en_US'),
('LOC_PEDIA_RELIGIONS_PAGE_OP_ZEUS_CHAPTER_HISTORY_PARA_1', 'Zeus is the sky and thunder god, who rules as king of the gods of Mount Olympus. Zeus is the child of Cronus and Rhea, the youngest of his siblings to be born, though sometimes reckoned the eldest as the others required disgorging from Cronus''s stomach.[NEWLINE][NEWLINE]He is married to Hera, by whom he is usually said to have fathered Ares, Hebe, and Hephaestus. At the oracle of Dodona, his consort was said to be Dione, by whom he fathered Aphrodite. Zeus was also infamous for his erotic escapades. These resulted in many godly and heroic offspring, including Athena, Apollo, Artemis, Hermes, Persephone, Dionysus, Perseus, Heracles, Helen of Troy, Minos, and the Muses.', 'en_US') ;
